version: '3.8'
services:
  # app service for your backend
  gesto-back:
    container_name: gesto-back
    restart: always
    image: ghcr.io/gesto-team/gesto-back/gesto-back
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URI=${DATABASE_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABSE_PORT=${DATABASE_PORT}
      - API_PORT=${API_PORT}
    ports:
      - '3001:3000'
    depends_on:
      - mongodb

  # start the mongodb service as container
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: gestodb
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
