version: '3.8'
services:
  # app service for your backend
  app:
    container_name: gesto-back
    restart: always
    image: ghcr.io/gesto-team/gesto-back/gesto-back
    ports:
      - '3001:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: fruitdb
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
